basedosdados/website

- ckanext-basedosdados/ckanext/basedosdados/template_functions.py
- ckanext-basedosdados/ckanext/basedosdados/templates/package/resource_read.html
@polvoazul @rdahis consegue testar aqui? Não estou conseguindo subir o Docker local...
> Atualiza exemplo do pacote em R

- ckanext-basedosdados/ckanext/basedosdados/actions/__init__.py
- ckanext-basedosdados/ckanext/basedosdados/actions/get.py
- ckanext-basedosdados/ckanext/basedosdados/actions/post.py
No futuro resolverá a issue #15 criando os seguintes endpoints:
---
As informações dos primeiros endpoints estão contidas no dicionário com nome:
- Título ~ title
- Tags ~ tags
- Link para base de dados - name
- Data da última atualização ~ metadata_modified
- Quantidade de tabelas - **necessário gerar**
- Quantidade de links externos - **necessário gerar**
- Tamanho ~ **não existe**
- Último usuário que atualizou a base - **não existe**
---
Problemas até agora:  
- Existe o campo format e o campo formato
- Não tenho certeza se podemos usar o endpoint do Hubspot
> [infra] add new endpoints

- configs/docker-compose.override.prod.yaml
- configs/nginx.conf
- configs/nginx.dev.conf
- docker-compose.override.yaml
- next/Dockerfile
- next/components/atoms/SiteHead.js
- next/components/molecules/Footer.js
- next/components/molecules/Menu.js
- next/components/organisms/DatabaseCard.js
- next/components/organisms/NewsCard.js
- next/next.config.js
- next/package.json
- next/pages/index.js
- next/pages/search.js
Esqueci de ver com o Fred que os comandos de dev e produção são diferentes.
Coloquei os commands de volta no dockerfile,
criei tbm um comando no yarn para realizar o build e start do Next na hora de deployar.
> [infra] renomeando endpoint do site para /_nxt e realizando alguns ajustes de Docker

- ckanext-basedosdados/ckanext/basedosdados/README.md
@polvoazul você também comentou:
- mudar validator para metadata
- mudar de nome package
- move classes padrões do ckan do package.py para outro arquivo
- mudar o nome de package para dataset
> [infra] add metadata documentation

- .github/workflows/check-links.yml
- .github/workflows/check-links/action.yml
- .github/workflows/check-links/crawler.py
- .github/workflows/check-links/to_markdown.py
Igual ao [pr](https://github.com/basedosdados/website/pull/17) anterior, mas dessa vez vou acertar o merge com squash.
> [infra] add link checker v2

- ckanext-basedosdados/ckanext/basedosdados/actions/get.py
- ckanext-basedosdados/ckanext/basedosdados/actions/openapi.json
- ckanext-basedosdados/ckanext/basedosdados/actions/openapi.yml
- ckanext-basedosdados/ckanext/basedosdados/plugin.py
- ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/fields_definitions.py
- configs/ckan.ini
pretende solucionar a issue #60
> [infra] endpoints de busca e tradução

- ckanext-basedosdados/ckanext/basedosdados/actions/get.py
- configs/ckan.ini
Soluciona um dos tópicos da issue #76.
Os `resource_type` válidos são `bdm_table` e `external_link`
> [infra] adiciona o filtro `resource_type` e `entity`

- ckanext-basedosdados/ckanext/basedosdados/validator/available_options/measurement_unit.py
- Inclusão de novas unidades de volume e de energia
- Reorganização de unidades de medida, separando lineares de áreas
> Measurement additions

- next/components/organisms/BdmTablePage.js
Atualização do código de exemplo em R sem SQL (v0.1.0 já rodando)
@brenodega28 indico para branch `develop` ou `master`?
> Update code sample to R package v0.1.0

- next/pages/api/datasets.js
- next/pages/index.js
* Conserta carrossel na home para conjuntos mais recentes. Closes #214.
> fix: popular to recent datasets in home

- next/components/molecules/Footer.js
Tentei entrar no grupo e percebi que o link não estava funcionando. Me passaram o link correto e resolvi abrir esse PR ajustando o footer
> fix: link whatsapp footer

- next/components/atoms/BigTitle.js
- next/components/atoms/SectionText.js
- next/components/molecules/Menu.js
- next/pages/quem-somos.js
> Nova página: Quem somos

- README.md
- ckanext-basedosdados/ckanext/basedosdados/README.md
- ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/__init__.py
- ckanext-basedosdados/ckanext/basedosdados/validator/resources/bdm/table/fields_definitions.py
> Criar o campo title em bdm tables

- ckanext-basedosdados/ckanext/basedosdados/validator/available_options/temporal_coverage.py
removendo a duplicacao da class _DateList e da função check_date_string_syntax
> fix duplicate _DateList validator

- ckanext-basedosdados/ckanext/basedosdados/validator/available_options/temporal_coverage.py
corrigindo as importações dos arquivos
> fix imports

- .github/workflows/cd.yml
* add: staging branch
* minor fix: rename prod environment
> Feat/branch staging (#339)

- ckanext-basedosdados/ckanext/basedosdados/actions/get.py
- ckanext-basedosdados/ckanext/basedosdados/virtual_fields/__init__.py
> Spatial coverage fix

- next/pages/api/datasets.js
- next/pages/dataset/index.js
- next/pages/index.js
Adicionada a pagina de Dados mais uma opção de ordenar: `Mais relevantes`
Na home temos agora as 5 tags mais populares listadas embaixo do input da Home
> Add feature: #369 and #381

- next/components/molecules/Cookies.js
- next/components/molecules/Footer.js
- next/components/molecules/ImgCrop.js
- next/components/molecules/Menu.js
- next/components/templates/main.js
- next/content/privacyPolicy.js
- next/content/serviceTerms.js
- next/package-lock.json
- next/package.json
- next/pages/api/user/deletePictureProfile.js
- next/pages/api/user/index.js
- next/pages/api/user/updatePictureProfile.js
- next/pages/contato.js
- next/pages/estudos-de-caso/[id].js
- next/pages/estudos-de-caso/index.js
- next/pages/perguntas-frequentes.js
- next/pages/precos.js
- next/pages/quem-somos.js
- next/pages/termos-e-privacidade.js
- next/pages/termos_e_politicas.js
- next/pages/user/[username].js
- next/pages/user/activate-account.js
- next/pages/user/login.js
- next/pages/user/password-recovery.js
- next/pages/user/register.js
- next/styles/imgCrop.module.css
https://equipeplataforma.atlassian.net/browse/EQP-110
https://equipeplataforma.atlassian.net/browse/EQP-160
https://equipeplataforma.atlassian.net/browse/EQP-163
https://equipeplataforma.atlassian.net/browse/EQP-159
> User config ajust

- next/components/atoms/TemporalCoverageDisplay.js
- next/components/molecules/ColumnDatasets.js
- next/pages/api/datasets/getColumnsBdmTable.js
Update temporal coverage of tables and columns
> fix: update temporal coverage

- next/components/molecules/ThemeCatalog.js
- next/pages/dataset/index.js
Adapt frontend to search update
> feat: adapt front for search v2

- next/components/molecules/ThemeCatalog.js
- next/pages/_app.js
- next/public/locales/en/app.json
- next/public/locales/es/app.json
- next/public/locales/pt/app.json
- Conserta o tooltip exibindo nomes na língua certa.
- Acrescenta tradução no `_app` para traduzir a página exibida em thumbnails.
> fix: ThemeCatalog tooltip. feat: app translation

- next/components/organisms/DatasetSearchCard.js
- next/components/organisms/DatasetThemeCatalogCard.js
- next/pages/search.js
cc. @laura-l-amaral @nayaramrsc
> Hide LAI filter

- next/pages/about-us.js
- next/pages/api/team/getAllPeople.js
- next/pages/api/team/getAllTeams.js
- next/pages/api/team/getCareerPeople.js
- next/pages/api/team/getTeamMembers.js
- next/public/locales/en/aboutUs.json
- next/public/locales/es/aboutUs.json
- next/public/locales/pt/aboutUs.json
Trabalhando na issue #1124. Esse é o passo de mudar a leitura de campos que eram STRING e agora passam a ser classes.
> feat: update API calls with temporary team_new and role_new

- next/content/userGuide/pt/br-me-caged.md
- next/content/userGuide/pt/br-me-cnpj.md
Este PR insere informações sobre linhas duplicadas em algumas partições no guia de uso
> [Update] user-guide br-me-cnpj

- next/components/molecules/Menu.js
[Issue](https://github.com/basedosdados/website/issues/1145) relacionada a essa feature
fix: update menu logo navigation to search page
> fix: update menu logo navigation to search page
